### ISSUE TITLE
event emitting wrong parameters

### ISSUE THREAD

**Issue by navin9000** [harendra-shakya/uniswap-unwrapped#1]
In the file UniswapV2Pair.sol  mint(address to) function is emiting the wrongly.

emit Mint(msg.sender, amount0, amount1);  //Here the caller contract is msg.sender  not the Liquidity Provider

the minted address is "to" , the event should be like

emit Mint(to, amount0, amount1);

**Comment by MisterDefender99** [comment]
Nope bro, msg.sender is the pair contract which u had created and to is the account who receives Liquidity tokens. Please check carefully.

**Comment by MisterDefender99** [comment]
BTW it is cloned repo from Uniswap officials how it can be wrong??
